backup_directory = "/backups"

[[projects]]
service = "first_service"
docker_compose = "/path/to/project/containing/docker-compose-file"
path = "/path/to/backup/in/container"

[[projects]]
service = "second_service"
docker_compose = "/path/to/another/project/containing/docker-compose-file"
path = "/path/to/backup/in/container"
backup_command = "zip -r second_service.zip ."