backup_directory = "/backups"

[[projects]]
service = "first_service"
docker_compose = "/path/to/project/containing/docker-compose-file"

[[projects]]
service = "second_service"
docker_compose = "/path/to/another/project/containing/docker-compose-file"
backup_command = "zip -r second_service.zip ."